name: MobMastery
main: com.i2.mobmastery.MobMastery
version: 1.1.1
description: Control Mobs Easily
load: STARTUP
loadbefore: [ExtraHardMode, MobArena]
commands:
  mobmastery:
    description: ModMastery Command
    aliases: mm
    usage: /<command> reload, /<command> sh MobName Amount
permissions:
  mobmastery.reload:
    description: Reload MobMastery config file
    default: false