name: MobMastery
main: com.i2.mobmastery.MobMastery
version: 1.1.1
description: Change Mob Health Easily.
commands:
  mobmastery:
    description: ModMastery Command
permissions:
    mobmastery.reload:
      description: Reload MobDamage config file
      default: false